### ISSUE TITLE
Issue in Dataset preparation

### ISSUE THREAD

**Issue by SnehaShukla937** [Bala93/Multi-task-deep-network#10]
During dataset preparation, I encountered challenges with calculating dist_mask, dist_contour, and dist_signed. The computation of these values is performed using the Matlab library, as indicated in the GitHub repository. I successfully obtained the contour and distance map in PNG format. Can you assist me in getting dist_mask, dist_contour, and dist_signed in a mat file?

**Comment by Bala93** [comment]
I successfully obtained the contour and distance map in PNG format -- distance map should not be in png format, it should be like a map file, because it will have float values.
